# Generated by Django 2.2.1 on 2019-09-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_price_1',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
