# Generated by Django 2.2.1 on 2019-09-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_ticket_price_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_price_2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
