# Generated by Django 2.2.1 on 2019-09-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_ticket_price_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_price',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_price_1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_price_2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
