# Generated by Django 2.2.1 on 2019-09-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20190911_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_quantity_1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_quantity_2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
