# Generated by Django 2.2.1 on 2019-09-11 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20190911_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_price_1',
            new_name='price_1',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_price_2',
            new_name='price_2',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_quantity_1',
            new_name='quantity_1',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_quantity_2',
            new_name='quantity_2',
        ),
    ]
