# Generated by Django 2.2.1 on 2019-09-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20190911_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='quantity_2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
