# Generated by Django 2.2.1 on 2019-09-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_remove_ticket_ticket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='bonus_1',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='bonus_2',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
