# Generated by Django 2.2.1 on 2019-09-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_auto_20190912_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='bonus_3',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='price_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='quantity_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_name_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
