# Generated by Django 2.2.1 on 2019-09-13 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_auto_20190912_1847'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketType',
        ),
    ]
